=== LBNL-ETA/LibraryFEMTherm/src/Schemas/Materials Schema/Materials.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:simpleType name="Roughness" final="restriction">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Very Rough"/>
			<xs:enumeration value="Rough"/>
			<xs:enumeration value="Medium Rough"/>
			<xs:enumeration value="Medium Smooth"/>
			<xs:enumeration value="Smooth"/>
			<xs:enumeration value="Very Smooth"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="TableValue">
		<xs:complexType>
			<xs:all>
				<xs:element name="x" type="xs:double"/>
				<xs:element name="y" type="xs:double"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="Table">
		<xs:sequence>
			<xs:element ref="TableValue" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="HygroThermal">
		<xs:all>
			<xs:element name="DefaultThickness" type="xs:double" minOccurs="0" maxOccurs="1"/>
			<xs:element name="MaterialInformation" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="BulkDensity" type="xs:double" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Porosity" type="xs:double" minOccurs="0" maxOccurs="1"/>
			<xs:element name="SpecificHeatCapacityDry" type="xs:double" minOccurs="0" maxOccurs="1"/>
			<xs:element name="ThermalConductivityDry" type="xs:double" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Roughness" type="Roughness" minOccurs="0" maxOccurs="1"/>
			<xs:element name="WaterVaporDiffusionResistanceFactor" type="xs:double" minOccurs="0" maxOccurs="1"/>
			<xs:element name="ReferenceWaterContent" type="xs:double" minOccurs="0" maxOccurs="1"/>
			<xs:element name="FreeWaterSaturation" type="xs:double" minOccurs="0" maxOccurs="1"/>
			<xs:element name="WaterAbsorptionCoefficient" type="xs:double" minOccurs="0" maxOccurs="1"/>
			<xs:element name="DryingFactor" type="xs:double" minOccurs="0" maxOccurs="1"/>
			<xs:element name="MoistureDependentThermalConductivitySupplement" type="xs:double" minOccurs="0" maxOccurs="1"/>
			<xs:element name="TypicalBuiltInMoisture" type="xs:double" minOccurs="0" maxOccurs="1"/>
			<xs:element name="TemperatureDependentThermalConducivitySupplement" type="xs:double" minOccurs="0" maxOccurs="1"/>
			<xs:element name="ThermalConductivityDesignValue" type="xs:double" minOccurs="0" maxOccurs="1"/>
			<xs:element name="MoistureStorageFunction" type="Table" minOccurs="0" maxOccurs="1"/>
			<xs:element name="LiquidTransportationCoefficientSuction" type="Table" minOccurs="0" maxOccurs="1"/>
			<xs:element name="LiquidTransportationCoefficientRedistribution" type="Table" minOccurs="0" maxOccurs="1"/>
			<xs:element name="ThermalConductivityMoistureDependent" type="Table" minOccurs="0" maxOccurs="1"/>
			<xs:element name="WaterVaporDiffusionResistanceFactorMoistureDependent" type="Table" minOccurs="0" maxOccurs="1"/>
			<xs:element name="ThermalConductivityTemperatureDependent" type="Table" minOccurs="0" maxOccurs="1"/>
			<xs:element name="EnthalpyTemperatureDependent" type="Table" minOccurs="0" maxOccurs="1"/>
		</xs:all>
	</xs:complexType>
	<xs:element name="HygroThermal" type="HygroThermal"/>
	<xs:complexType name="OpticalProperties">
		<xs:all>
			<xs:element name="Transmittance" type="xs:double"/>
			<xs:element name="Reflectance" type="xs:double"/>
		</xs:all>
	</xs:complexType>
	<xs:element name="OpticalProperties" type="OpticalProperties"/>
	<xs:complexType name="OpticalSide">
		<xs:all>
			<xs:element name="Front" type="OpticalProperties"/>
			<xs:element name="Back" type="OpticalProperties"/>
		</xs:all>
	</xs:complexType>
	<xs:element name="OpticalSide" type="OpticalSide"/>
	<xs:complexType name="OpticalType">
		<xs:all>
			<xs:element name="Direct" type="OpticalSide"/>
			<xs:element name="Diffuse" type="OpticalSide"/>
		</xs:all>
	</xs:complexType>
	<xs:element name="OpticalType" type="OpticalType"/>
	<xs:complexType name="Infrared">
		<xs:all>
			<xs:element name="Transmittance" type="xs:double" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Emissivity-Front" type="xs:double" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Emissivity-Back" type="xs:double" minOccurs="0" maxOccurs="1"/>
		</xs:all>
	</xs:complexType>
	<xs:complexType name="Integrated">
		<xs:all>
			<xs:element name="Infrared" type="Infrared"/>
			<xs:element name="Solar" type="OpticalType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Visible" type="OpticalType" minOccurs="0" maxOccurs="1"/>
		</xs:all>
	</xs:complexType>
	<xs:element name="Integrated" type="Integrated"/>
	<xs:complexType name="Optical">
		<xs:all>
			<xs:element name="Integrated" type="Integrated" minOccurs="0" maxOccurs="1"/>
		</xs:all>
	</xs:complexType>
	<xs:element name="Optical" type="Optical"/>
	<xs:complexType name="Solid">
		<xs:all>
			<xs:element name="HygroThermal" type="HygroThermal" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Optical" type="Optical" minOccurs="0" maxOccurs="1"/>
		</xs:all>
	</xs:complexType>
	<xs:complexType name="WINDOW">
		<xs:all>
			<xs:element name="Path" type="xs:string"/>
			<xs:element name="Name" type="xs:string"/>
			<xs:element name="ID" type="xs:integer"/>
		</xs:all>
	</xs:complexType>
	<xs:complexType name="Database">
		<xs:all>
			<xs:element name="WINDOW" type="WINDOW" minOccurs="0" maxOccurs="1"/>
		</xs:all>
	</xs:complexType>
	<xs:element name="Material">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="UUID" type="xs:string"/>
				<xs:element name="Name" type="xs:string"/>
				<xs:element name="ProjectName" type="xs:string" minOccurs="0" maxOccurs="1"/>
				<xs:element name="Protected" type="xs:boolean"/>
				<xs:element name="Color" type="xs:string"/>
				<xs:element name="Database" type="Database" minOccurs="0" maxOccurs="1"/>
				<xs:element name="Solid" type="Solid"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="Materials" mixed="true">
		<xs:sequence>
			<xs:element name="Version" type="xs:string"/>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="Material"/>
			</xs:choice>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="Materials" type="Materials"/>
</xs:schema>

=== LBNL-ETA/LibraryFEMTherm/src/Schemas/Materials Schema/Materials.xml
<Materials xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="Materials.xsd">
	<Version>1</Version>
    <Material>
        <UUID>8dd145d0-5f30-11ea-bc55-0242ac130003</UUID>
        <Name>Laminated panel</Name>
        <Protected>true</Protected>
        <Color>0x008054</Color>
        <Solid>
            <HygroThermal>
                <DefaultThickness>0.01</DefaultThickness>
                <MaterialInformation>NA</MaterialInformation>
                <BulkDensity>450</BulkDensity>
                <Porosity>0.55</Porosity>
                <SpecificHeatCapacityDry>1400</SpecificHeatCapacityDry>
                <ThermalConductivityDry>0.125</ThermalConductivityDry>
                <WaterVaporDiffusionResistanceFactor>203</WaterVaporDiffusionResistanceFactor>
                <MoistureStorageFunction>
                    <TableValue>
                        <x>0</x>
                        <y>0</y>
                    </TableValue>
                    <TableValue>
                        <x>0.1</x>
                        <y>37</y>
                    </TableValue>
                    <TableValue>
                        <x>0.3</x>
                        <y>45</y>
                    </TableValue>
                    <TableValue>
                        <x>0.5</x>
                        <y>53</y>
                    </TableValue>
                    <TableValue>
                        <x>0.7</x>
                        <y>64</y>
                    </TableValue>
                    <TableValue>
                        <x>0.8</x>
                        <y>73</y>
                    </TableValue>
                    <TableValue>
                        <x>0.9</x>
                        <y>89</y>
                    </TableValue>
                    <TableValue>
                        <x>0.93</x>
                        <y>98</y>
                    </TableValue>
                    <TableValue>
                        <x>0.95</x>
                        <y>107</y>
                    </TableValue>
                    <TableValue>
                        <x>0.99</x>
                        <y>159</y>
                    </TableValue>
                    <TableValue>
                        <x>0.995</x>
                        <y>185</y>
                    </TableValue>
                    <TableValue>
                        <x>0.999</x>
                        <y>251</y>
                    </TableValue>
                    <TableValue>
                        <x>0.9995</x>
                        <y>281</y>
                    </TableValue>
                    <TableValue>
                        <x>0.9999</x>
                        <y>347</y>
                    </TableValue>
                    <TableValue>
                        <x>1</x>
                        <y>534</y>
                    </TableValue>
                </MoistureStorageFunction>
                <LiquidTransportationCoefficientSuction>
                    <TableValue>
                        <x>0</x>
                        <y>0</y>
                    </TableValue>
                    <TableValue>
                        <x>73</x>
                        <y>4e-12</y>
                    </TableValue>
                    <TableValue>
                        <x>534</x>
                        <y>5e-12</y>
                    </TableValue>
                </LiquidTransportationCoefficientSuction>
                <LiquidTransportationCoefficientRedistribution>
                    <TableValue>
                        <x>0</x>
                        <y>0</y>
                    </TableValue>
                    <TableValue>
                        <x>57</x>
                        <y>5.2e-11</y>
                    </TableValue>
                    <TableValue>
                        <x>65</x>
                        <y>7e-11</y>
                    </TableValue>
                    <TableValue>
                        <x>534</x>
                        <y>1e-10</y>
                    </TableValue>
                </LiquidTransportationCoefficientRedistribution>
                <ThermalConductivityMoistureDependent>
                    <TableValue>
                        <x>0</x>
                        <y>0.12</y>
                    </TableValue>
                    <TableValue>
                        <x>534</x>
                        <y>0.12</y>
                    </TableValue>
                </ThermalConductivityMoistureDependent>
                <ThermalConductivityTemperatureDependent>
                    <TableValue>
                        <x>10</x>
                        <y>0.12</y>
                    </TableValue>
                </ThermalConductivityTemperatureDependent>
            </HygroThermal>
            <Optical>
                <Integrated>
                    <Infrared>
                        <Transmittance>0</Transmittance>
                        <Emissivity-Front>0.9</Emissivity-Front>
                        <Emissivity-Back>0.9</Emissivity-Back>
                    </Infrared>
                </Integrated>
            </Optical>
        </Solid>
    </Material>
    <Material>
        <UUID>8dd149b8-5f30-11ea-bc55-0242ac130003</UUID>
        <Name>Aerated Concrete</Name>
        <Protected>true</Protected>
        <Color>0xFF8080</Color>
        <Solid>
            <HygroThermal>
                <DefaultThickness>0.2</DefaultThickness>
                <MaterialInformation>NA</MaterialInformation>
                <BulkDensity>400</BulkDensity>
                <Porosity>0.81</Porosity>
                <SpecificHeatCapacityDry>850</SpecificHeatCapacityDry>
                <ThermalConductivityDry>0.1</ThermalConductivityDry>
                <WaterVaporDiffusionResistanceFactor>7.9</WaterVaporDiffusionResistanceFactor>
                <MoistureStorageFunction>
                    <TableValue>
                        <x>0</x>
                        <y>0</y>
                    </TableValue>
                    <TableValue>
                        <x>0.5</x>
                        <y>3.1</y>
                    </TableValue>
                    <TableValue>
                        <x>0.8</x>
                        <y>8.4</y>
                    </TableValue>
                    <TableValue>
                        <x>0.93</x>
                        <y>18</y>
                    </TableValue>
                    <TableValue>
                        <x>0.964</x>
                        <y>116</y>
                    </TableValue>
                    <TableValue>
                        <x>0.99</x>
                        <y>266</y>
                    </TableValue>
                    <TableValue>
                        <x>0.995</x>
                        <y>269</y>
                    </TableValue>
                    <TableValue>
                        <x>0.999</x>
                        <y>277</y>
                    </TableValue>
                    <TableValue>
                        <x>1</x>
                        <y>380</y>
                    </TableValue>
                </MoistureStorageFunction>
                <LiquidTransportationCoefficientSuction>
                    <TableValue>
                        <x>0</x>
                        <y>0</y>
                    </TableValue>
                    <TableValue>
                        <x>3.1</x>
                        <y>2e-10</y>
                    </TableValue>
                    <TableValue>
                        <x>38</x>
                        <y>5.4e-09</y>
                    </TableValue>
                    <TableValue>
                        <x>265</x>
                        <y>1.1e-08</y>
                    </TableValue>
                    <TableValue>
                        <x>342</x>
                        <y>2e-08</y>
                    </TableValue>
                    <TableValue>
                        <x>380</x>
                        <y>1e-07</y>
                    </TableValue>
                </LiquidTransportationCoefficientSuction>
                <LiquidTransportationCoefficientRedistribution>
                    <TableValue>
                        <x>0</x>
                        <y>0</y>
                    </TableValue>
                    <TableValue>
                        <x>3.1</x>
                        <y>2e-10</y>
                    </TableValue>
                    <TableValue>
                        <x>38</x>
                        <y>4.2e-10</y>
                    </TableValue>
                    <TableValue>
                        <x>265</x>
                        <y>7.2e-10</y>
                    </TableValue>
                    <TableValue>
                        <x>342</x>
                        <y>4e-09</y>
                    </TableValue>
                    <TableValue>
                        <x>380</x>
                        <y>2.2e-08</y>
                    </TableValue>
                </LiquidTransportationCoefficientRedistribution>
                <ThermalConductivityMoistureDependent>
                    <TableValue>
                        <x>0</x>
                        <y>0.1</y>
                    </TableValue>
                    <TableValue>
                        <x>380</x>
                        <y>0.1</y>
                    </TableValue>
                </ThermalConductivityMoistureDependent>
                <ThermalConductivityTemperatureDependent>
                    <TableValue>
                        <x>10</x>
                        <y>0.1</y>
                    </TableValue>
                </ThermalConductivityTemperatureDependent>
            </HygroThermal>
            <Optical>
                <Integrated>
                    <Infrared>
                        <Transmittance>0</Transmittance>
                        <Emissivity-Front>0.9</Emissivity-Front>
