=== LBNL-ETA/LibraryFEMTherm/src/Schemas/Gases Schema/Gases.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:complexType name="Coefficients">
		<xs:all>
			<xs:element name="A" type="xs:double" minOccurs="1" maxOccurs="1"/>
			<xs:element name="B" type="xs:double" minOccurs="1" maxOccurs="1"/>
			<xs:element name="C" type="xs:double" minOccurs="1" maxOccurs="1"/>
		</xs:all>
	</xs:complexType>
	<xs:element name="Coefficients" type="Coefficients"/>
	<xs:complexType name="Record" abstract="true">
		<xs:sequence>
			<xs:element name="UUID" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="Name" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="Protected" type="xs:boolean" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Properties">
		<xs:all>
			<xs:element name="MolecularWeight" type="xs:double" minOccurs="1" maxOccurs="1"/>
			<xs:element name="SpecificHeatRatio" type="xs:double" minOccurs="1" maxOccurs="1"/>
			<xs:element name="Conductivity" type="Coefficients" minOccurs="1" maxOccurs="1"/>
			<xs:element name="Viscosity" type="Coefficients" minOccurs="1" maxOccurs="1"/>
			<xs:element name="SpecificHeat" type="Coefficients" minOccurs="1" maxOccurs="1"/>
		</xs:all>
	</xs:complexType>
	<xs:complexType name="PureGas">
		<xs:complexContent>
			<xs:extension base="Record">
				<xs:sequence>
					<xs:element name="Properties" type="Properties" minOccurs="1" maxOccurs="1"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="PureGas" type="PureGas"/>
	<xs:complexType name="Component">
		<xs:all>
			<xs:element name="Fraction" type="xs:double" minOccurs="1" maxOccurs="1"/>
			<xs:element name="PureGas" type="xs:string" minOccurs="1" maxOccurs="1"/>
		</xs:all>
	</xs:complexType>
	<xs:element name="Component" type="Component"/>
	<xs:complexType name="Components">
		<xs:all>
			<xs:element name="Component" type="Components" minOccurs="1"/>
		</xs:all>
	</xs:complexType>
	<xs:element name="Components" type="Components"/>
	<xs:complexType name="Gas">
		<xs:complexContent>
			<xs:extension base="Record">
				<xs:sequence>
					<xs:element name="Components" minOccurs="1" maxOccurs="1"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="Gas" type="Gas"/>
	<xs:complexType name="Gases">
        <xs:sequence>
            <xs:element name="Version" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="PureGas"/>
                <xs:element ref="Gas"/>
            </xs:choice>
        </xs:sequence>
    </xs:complexType>
	<xs:element name="Gases" type="Gases"/>
</xs:schema>

=== LBNL-ETA/LibraryFEMTherm/src/Schemas/Gases Schema/Gases.xml
<?xml version="1.0" encoding="utf-8"?>
<Gases xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="Gases.xsd">
	<Version>1</Version>
	<PureGas>
		<UUID>8d33196f-f052-46e6-8353-bccb9a779f9c</UUID>
		<Name>Air</Name>
		<Protected>true</Protected>
		<Properties>
			<MolecularWeight>28.97</MolecularWeight>
			<SpecificHeatRatio>1.4</SpecificHeatRatio>
			<Conductivity>
				<A>0.002873</A>
				<B>0.0000776</B>
				<C>0</C>
			</Conductivity>
			<Viscosity>
				<A>0.000003723</A>
				<B>4.94E-08</B>
				<C>0</C>
			</Viscosity>
			<SpecificHeat>
				<A>1002.737</A>
				<B>0.012324</B>
				<C>0</C>
			</SpecificHeat>
		</Properties>
	</PureGas>
	<PureGas>
		<UUID>444d94e4-326e-4c1c-aef1-666771b569cd</UUID>
		<Name>Argon</Name>
		<Protected>true</Protected>
		<Properties>
			<MolecularWeight>39.948</MolecularWeight>
			<SpecificHeatRatio>1.67</SpecificHeatRatio>
			<Conductivity>
				<A>0.002285</A>
				<B>0.00005149</B>
				<C>0</C>
			</Conductivity>
			<Viscosity>
				<A>0.000003379</A>
				<B>6.451E-08</B>
				<C>0</C>
			</Viscosity>
			<SpecificHeat>
				<A>521.9285</A>
				<B>0</B>
				<C>0</C>
			</SpecificHeat>
		</Properties>
	</PureGas>
	<PureGas>
		<UUID>9d20da3f-51e2-4a86-832f-cd2e0feacd97</UUID>
		<Name>Krypton</Name>
		<Protected>true</Protected>
		<Properties>
			<MolecularWeight>248.0907</MolecularWeight>
			<SpecificHeatRatio>1.68</SpecificHeatRatio>
			<Conductivity>
				<A>0.0009443</A>
				<B>0.00002826</B>
				<C>0</C>
			</Conductivity>
			<Viscosity>
				<A>0.000002213</A>
				<B>7.777E-08</B>
				<C>0</C>
			</Viscosity>
			<SpecificHeat>
				<A>248.0907</A>
				<B>0</B>
				<C>0</C>
			</SpecificHeat>
		</Properties>
	</PureGas>
	<PureGas>
		<UUID>2594d8ef-6c10-488b-a272-5b6a4e4b5a15</UUID>
		<Name>Xenon</Name>
		<Protected>true</Protected>
		<Properties>
			<MolecularWeight>131.3</MolecularWeight>
			<SpecificHeatRatio>1.66</SpecificHeatRatio>
			<Conductivity>
				<A>0.0004538</A>
				<B>0.00001723</B>
				<C>0</C>
			</Conductivity>
			<Viscosity>
				<A>0.000001069</A>
				<B>7.414E-08</B>
				<C>0</C>
			</Viscosity>
			<SpecificHeat>
				<A>158.3397</A>
				<B>0</B>
				<C>0</C>
			</SpecificHeat>
		</Properties>
	</PureGas>
	<Gas>
		<UUID>6c2409e9-5296-46c1-be11-9029b59a549b</UUID>
		<Name>Air</Name>
		<Protected>true</Protected>
		<Components>
			<Component>
				<Fraction>
					1
				</Fraction>
				<PureGas>
					Air
				</PureGas>
			</Component>
		</Components>
	</Gas>
	<Gas>
		<UUID>78877879-21bd-4a7f-a735-2f981aad0b8d</UUID>
		<Name>Argon</Name>
		<Protected>true</Protected>
		<Components>
			<Component>
				<Fraction>
					1
				</Fraction>
				<PureGas>
					Argon
				</PureGas>
			</Component>
		</Components>
	</Gas>
	<Gas>
		<UUID>66d89cf9-a32e-4fd7-80cc-db4960bc3214</UUID>
		<Name>Krypton</Name>
		<Protected>true</Protected>
		<Components>
			<Component>
				<Fraction>
					1
				</Fraction>
				<PureGas>
					Krypton
				</PureGas>
			</Component>
		</Components>
	</Gas>
	<Gas>
		<UUID>0746cb5d-36a0-4581-841c-15a8bb33bacb</UUID>
		<Name>Xenon</Name>
		<Protected>true</Protected>
		<Components>
			<Component>
				<Fraction>
					1
				</Fraction>
				<PureGas>
					Xenon
				</PureGas>
			</Component>
		</Components>
	</Gas>
	<Gas>
		<UUID>37881919-7cdf-4428-bf5c-10702bc78415</UUID>
		<Name>Air 10%/Argon 90%</Name>
		<Protected>true</Protected>
		<Components>
			<Component>
				<Fraction>
					0.1
				</Fraction>
				<PureGas>
					Air
				</PureGas>
			</Component>
			<Component>
				<Fraction>
					0.9
				</Fraction>
				<PureGas>
					Argon
				</PureGas>
			</Component>
		</Components>
	</Gas>
</Gases>
