=== LBNL-ETA/LibraryFEMTherm/src/Schemas/CMA Schema/CMALibrary.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<!-- Definition for Option type (Low or High) -->
	<xs:simpleType name="OptionType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Low"/>
			<xs:enumeration value="High"/>
		</xs:restriction>
	</xs:simpleType>
	<!-- Generic entry for both SingleLayer and DoubleLayer -->
	<xs:element name="Options">
		<xs:complexType>
			<xs:all>
				<xs:element name="Glazing" type="OptionType" minOccurs="1" maxOccurs="1"/>
				<xs:element name="Spacer" type="OptionType" minOccurs="1" maxOccurs="1"/>
				<xs:element name="hcin" type="xs:double" minOccurs="1" maxOccurs="1"/>
				<xs:element name="hcout" type="xs:double" minOccurs="1" maxOccurs="1"/>
				<xs:element name="EmissivityIn" type="xs:double" minOccurs="1" maxOccurs="1"/>
				<xs:element name="EmissivityOut" type="xs:double" minOccurs="1" maxOccurs="1"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="SingleLayer">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Thickness" type="xs:double"/>
				<xs:element name="Conductivity" type="xs:double"/>
				<xs:element ref="Options" minOccurs="4" maxOccurs="4"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="DoubleLayer">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Thickness1" type="xs:double"/>
				<xs:element name="Thickness2" type="xs:double"/>
				<xs:element name="Conductivity1" type="xs:double"/>
				<xs:element name="Conductivity2" type="xs:double"/>
				<xs:element ref="Options" minOccurs="4" maxOccurs="4"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="GlazingConductance">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Low" type="xs:double"/>
				<xs:element name="High" type="xs:double"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="SpacerConductivity">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Low" type="xs:double"/>
				<xs:element name="High" type="xs:double"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<!-- Define the main complex type for the table -->
	<xs:element name="Environment">
		<xs:complexType>
			<xs:all>
				<xs:element name="Tin" type="xs:double"/>
				<xs:element name="Tout" type="xs:double"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="CMAData">
		<xs:complexType>
			<xs:all>
			  <xs:element name="Version" type="xs:string" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="Environment" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="GlazingConductance" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="SpacerConductivity" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="SingleLayer" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="DoubleLayer" minOccurs="1" maxOccurs="1"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== LBNL-ETA/LibraryFEMTherm/src/Schemas/CMA Schema/CMALibrary.xml
<?xml version="1.0" encoding="utf-8"?>
<CMAData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="CMALibrary.xsd">
	<Version>1</Version>
	<Environment>
		<Tin>21</Tin>
		<Tout>-18</Tout>
	</Environment>
	<GlazingConductance>
		<Low>0.498817</Low>
		<High>5.880546</High>
	</GlazingConductance>
	<SpacerConductivity>
		<Low>0.01</Low>
		<High>10</High>
	</SpacerConductivity>
	<SingleLayer>
		<Thickness>0.006</Thickness>
		<Conductivity>1</Conductivity>
		<Options>
			<Glazing>Low</Glazing>
			<Spacer>Low</Spacer>
			<hcin>3.415185</hcin>
			<hcout>26</hcout>
			<EmissivityIn>0.026</EmissivityIn>
			<EmissivityOut>0.84</EmissivityOut>
		</Options>
		<Options>
			<Glazing>Low</Glazing>
			<Spacer>High</Spacer>
			<hcin>3.415185</hcin>
			<hcout>26</hcout>
			<EmissivityIn>0.026</EmissivityIn>
			<EmissivityOut>0.84</EmissivityOut>
		</Options>
		<Options>
			<Glazing>High</Glazing>
			<Spacer>Low</Spacer>
			<hcin>3.529954</hcin>
			<hcout>26</hcout>
			<EmissivityIn>0.84</EmissivityIn>
			<EmissivityOut>0.84</EmissivityOut>
		</Options>
		<Options>
			<Glazing>High</Glazing>
			<Spacer>High</Spacer>
			<hcin>3.529954</hcin>
			<hcout>26</hcout>
			<EmissivityIn>0.84</EmissivityIn>
			<EmissivityOut>0.84</EmissivityOut>
		</Options>
	</SingleLayer>
	<DoubleLayer>
		<Thickness1>0.006</Thickness1>
		<Thickness2>0.006</Thickness2>
		<Conductivity1>1</Conductivity1>
		<Conductivity2>1</Conductivity2>
		<Options>
			<Glazing>Low</Glazing>
			<Spacer>Low</Spacer>
			<hcin>1.854252</hcin>
			<hcout>26</hcout>
			<EmissivityIn>0.84</EmissivityIn>
			<EmissivityOut>0.84</EmissivityOut>
		</Options>
		<Options>
			<Glazing>Low</Glazing>
			<Spacer>High</Spacer>
			<hcin>1.854252</hcin>
			<hcout>26</hcout>
			<EmissivityIn>0.84</EmissivityIn>
			<EmissivityOut>0.84</EmissivityOut>
		</Options>
		<Options>
			<Glazing>High</Glazing>
			<Spacer>Low</Spacer>
			<hcin>2.866122</hcin>
			<hcout>26</hcout>
			<EmissivityIn>0.84</EmissivityIn>
			<EmissivityOut>0.84</EmissivityOut>
		</Options>
		<Options>
			<Glazing>High</Glazing>
			<Spacer>High</Spacer>
			<hcin>2.866122</hcin>
			<hcout>26</hcout>
			<EmissivityIn>0.84</EmissivityIn>
			<EmissivityOut>0.84</EmissivityOut>
		</Options>
	</DoubleLayer>
</CMAData>
